### ISSUE TITLE
Make keyword configurable

### ISSUE THREAD

**Issue by Sophivorus** [alvinhochun/chrome-bookmark-search#16] opened 2022-06-11 02:47 UTC
First off, thanks for this extension, it really boosts my productivity. This request may sound a but trivial, but since an extension like this is made for speed, it really surprised me that I couldn't change the keyword "bm" to just "b". Hope one day I can!

**Comment by alvinhochun** [comment] 2022-06-11 14:51
You are not the first one to ask but it is limited by the extension API. It only allows specifying one keyword hardcoded in the manifest. You can download the source code, change the keyword in the manifest, then load the extension into Chrome.

Duplicate of #3

**Closed by alvinhochun** 2022-06-11 14:51 UTC
